server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: localhost
      post: 8500
      discovery:
        instance-id: ${spring.application.name}