server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
           - Path=/payment/get/**    #断言,路径相匹配的进行路由

        - id: payment-routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
           - Path=/payment/lb/**
             #在此时间之后可以访问，否则报404
             #- After=2020-12-26T15:58:03.543+08:00[Asia/Shanghai]
             #在此时间之前可以访问，否则报404
             #- Before=2020-12-26T14:58:03.543+08:00[Asia/Shanghai]
             #在此时间段之内可以访问
             #- Between=2020-12-26T14:58:03.543+08:00[Asia/Shanghai],020-12-26T15:58:03.543+08:00[Asia/Shanghai]
           #- Cookie=username,zhikun
           #- Host=**.baidu.com
           #- Header=X-Request-Id,\d+ #请求头要有X-Request-id属性并且值为整数的正则表达式


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
